version: "3.8"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: himanshi
      MYSQL_DATABASE: devops
    container_name: mysql
    ports: 
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - two-tier
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"] 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  flask:
    image: himanshi3112/two-tier-app:latest
    container_name: two-tier-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: himanshi
      MYSQL_DB: devops
      MYSQL_HOST: mysql
    networks:
      - two-tier
    depends_on:
      - mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s

volumes:
  mysql-data:
networks:
  two-tier:

